### PR TITLE
Fix #80: SEO tag for Qute

### LINKED ISSUE #80: [frontmatter] Add an easy way to deal with SEO
We need a similar feature set as https://github.com/jekyll/jekyll-seo-tag

### PR DESCRIPTION
**Pull request by melloware**
Fix #80 

Just getting this started this has a lot of what Jekyll has so far but some open questions.

- [x] ~~Date tag we need to figure out what is the correct format as Jekyll does this `{{ page.date | date_to_xmlschema }}`~~
- [x] ~~Where to get `author` data?~~
- [x] ~~For `generator` tag they use a version but didn't know if that was available. `content="Jekyll v{{ jekyll.version }}"`~~
- [x] ~~Where to get `page.locale` data?~~
- [x] ~~How to generate `previous`  and `next` pages.  Right now it prints out "1".~~
- [x] ~~Image URL generating issue see below...~~

generating wrong Image URLs
```xml
<!-- SEO IMAGE -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:image:src" content="/assets/img/https://images.unsplash.com/photo-1563206767-5b18f218e8de?q=80&amp;w=3538&amp;auto=format&amp;fit=crop&amp;ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D">
  <meta property="og:image" content="/assets/img/https://images.unsplash.com/photo-1563206767-5b18f218e8de?q=80&amp;w=3538&amp;auto=format&amp;fit=crop&amp;ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
```

### CODE REVIEW

**Comment by ia3andy** [comment]
> I did this just to get started but I think what you want is to pass individual properties per element from `page` and `site` so each SEO element can be passed in correct?

Not exactly, split the seo tag in multiple tags, then user can choose to pick those tags manually instead

**Comment by ia3andy** [comment]
But keep the seo tag that group it all and very easy to call

**Comment by melloware** [comment]
Got it.

**Comment by ia3andy** [comment]
For images: https://github.com/quarkiverse/quarkus-roq/blob/main/blog/site/_layouts/post.html#L10

**Comment by melloware** [comment]
Thanks that fixed images!

**Comment by melloware** [comment]
Only open question is how should the next and previous URL's be.

Right now it does this.

```xml
<!-- SEO PAGINATOR -->
<link rel="prev" href="[/posts/page1](view-source:http://localhost:8080/posts/page1)" />
```

**Pull request merged**
