### PR TITLE
Bump build.yml to JDK 21

### PR DESCRIPTION
**Pull request by gastaldi**
Trying to reproduce the error in https://github.com/quarkiverse/quarkus-roq/issues/108

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
OK weird its passing on CI/CD

**Comment by melloware** [comment]
yes it did.  Very weird.

**Comment by melloware** [comment]
We had a similar weird one where it was passing Windows CI/CD but failing on my machine: https://github.com/quarkiverse/quarkus-roq/pull/100

We still have no idea why it was passing on CI/CD it should not have.

**Comment by melloware** [comment]
It would't matter I am using Adoptium would it?  What OpenJDK does the CI/CD use?

**Comment by gastaldi** [comment]
Temurin AFAIK (which is the same)

**Pull request merged**
