### PR TITLE
Introduce Roq extension api

### PR DESCRIPTION
**Pull request by ia3andy**
Allow extension to contribute to Roq:
- Read pages and collections data (and access links)
- Publish Roq pages

This will allow to create an extension similar to [jekyll tagging](https://github.com/pattex/jekyll-tagging)

### CODE REVIEW

**Comment by melloware** [comment]
Conflict?

**Comment by ia3andy** [comment]
> Conflict?

@melloware ok there was a small mistake I didn't catch in the seo-tag PR. I am not sure why @mcruzdev added this `tag`:
https://github.com/quarkiverse/quarkus-roq/commit/598c85018b4a14be4f4d820aa34f5c761dddef98#diff-44353de755a5ff8603b88648652595fee47d5b8ad1c418869de30751a7f6baa3

**Comment by ia3andy** [comment]
@mcruzdev @melloware FYI the logic is the exact same, just I split it in phases and builditems to make it easy to plug in there.

**Review by melloware — APPROVED** [review]

**Comment by ia3andy** [comment]
Waiting for web-bundler release to fix windows paths

**Pull request merged**
