### PR TITLE
Introduce quarkus-roq-plugin-asciidoc

### LINKED ISSUE #169: Make sure asciidoc works as expected

### PR DESCRIPTION
**Pull request by jtama**
Fixes #169

### CODE REVIEW

**Comment by melloware** [comment]
@all-contributors add @jtama for code

**Comment by melloware** [comment]
Interesting it looks like we have some native support to work on I am surprised Quarkus Qute AsciiDoc never ran into this?

**Comment by melloware** [comment]
Yeah I am looking at Qute AsciiDoc and it has nothing for Native support really. I think we need to add `io.yupiik.tools.ascii2svg.Svg` for RegisterForReflection in the Qute AscissDoc Deployment

**Comment by melloware** [comment]
OK I submitted a fix to Qute

**Comment by jtama** [comment]
@ia3andy Many thanks, quarkus + asciidoc + static generation are a perfect match, plus a bonus point for jbang \o/

**Comment by ia3andy** [comment]
Let's merge and fix the native later

**Pull request merged**
