### PR TITLE
Mastodon link verified

### PR DESCRIPTION
**Pull request by jotak**
"rel=me" attributes allows to make the link verified on mastodon, when added to the account profile: https://joinmastodon.org/verification

### CODE REVIEW

**Comment by jotak** [comment]
PS: this would assume users configure their `social-mastodon` data with their own account.
I guess another option would be to make that optional, maybe something like:
```
    {#if site.data.social-mastodon??}

    {#if site.data.social-mastodon.verify??}
    <li class="mastodon"><a href="{site.data.social-mastodon}" rel="me" target="_blank"><i class="fa-brands fa-mastodon"></i></a></li>
    {#else}
    <li class="mastodon"><a href="{site.data.social-mastodon}" target="_blank"><i class="fa-brands fa-mastodon"></i></a></li>
    {/if}
    {/if}
```
 ?

**Comment by melloware** [comment]
Want to submit a PR?

**Comment by jotak** [comment]
@melloware this is a PR 😄

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Sorry got this on my email thought it was an issue. Looks great!

**Comment by melloware** [comment]
@all-contributors add @jotak for code

**Pull request merged**
