### PR TITLE
Plugin Series

### LINKED ISSUE #294: Give the ability to make posts series
The idea is to be able to add specify that a post is part of a serie, and offer automatic navigation to other posts fro the same serie.

It gives strong coupling between multiple posts.

I know it exists at least on dev.to : 

image

I have made something for our internal use case, and added i18n for english and french, but I am not 100% percent I choose the right path. 

I can provide a PR as base for more discussion.

### PR DESCRIPTION
**Pull request by jtama**
fixes #294

### CODE REVIEW

**Comment by ia3andy** [comment]
ah sorry you did :)

**Comment by jtama** [comment]
Yes, I sometimes forget to sync repositories.

And I forgot to say that I am NOT a front developer ;)

**Review by melloware — APPROVED** [review]
LGTM but will let others review too

**Comment by jtama** [comment]
Ok I think there's something to do with @DataMapping, I thought it would automatically register my record for reflexion, but it does so only if there is a `RoqDataBuildItem` linked to it. It's not the case for me, the data is generated through a recorder.

Anyway, I fixed the native build, but I had a small talk with @ia3andy who will help for ui design, mine is really, really poor.

**Comment by ia3andy** [comment]
At some point it might make sense to allow having more stuff to the FM series to define sorting and other stuff.;

**Pull request merged**
